export const REACTION_RATE_LIMIT_REQUESTS = 10
export const REACTION_RATE_LIMIT_WINDOW_SECONDS = 60

export const COMMENT_RATE_LIMIT_REQUESTS = 5
export const COMMENT_RATE_LIMIT_WINDOW_SECONDS = 60

export const VIEW_RATE_LIMIT_REQUESTS = 1
export const VIEW_RATE_LIMIT_WINDOW_SECONDS = 3600

export const CONTACT_RATE_LIMIT_REQUESTS = 3
export const CONTACT_RATE_LIMIT_WINDOW_SECONDS = 3600

export const NEWSLETTER_RATE_LIMIT_REQUESTS = 3
export const NEWSLETTER_RATE_LIMIT_WINDOW_SECONDS = 3600
